--- #YAML:1.0
name:               Net-Whois-RIS
version:            0.1
abstract:           Whois lookup on RIPE RIS 
author:
    - Alexandre Dulaunoy <adulau@foo.be>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket:  0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
